### Variables
@baseUrl = http://localhost:3000/api/v1/

### /company
GET  {{baseUrl}}company HTTP/1.1

###

### /company:uuid
GET  {{baseUrl}}company/2edefc50-6e8f-4d6e-9ff2-15d44cc6e927 HTTP/1.1

###


### /company:uuid
DELETE   {{baseUrl}}company/ea43c9d1-1275-49c9-ba15-53a7902fb811 HTTP/1.1

###


### /company:uuid
PUT  {{baseUrl}}company/2edefc50-6e8f-4d6e-9ff2-15d44cc6e927 HTTP/1.1
Content-Type: application/json

{
  "name": "teste 02",
  "cnpj": 85045712000188,
  "address": "rua sei lá 2",
  "phone": "(95) 2454-8232",
  "numberMotocycles": 10,
  "numberCars": 10
}


### company/create
POST {{baseUrl}}company HTTP/1.1
Content-Type: application/json

{
  "name": "teste 01",
  "cnpj":85045712000180,
  "address": "rua sei lá",
  "phone":"(95) 2454-8231",
  "numberMotocycles": 10,
  "numberCars": 10
}
###